server:
  port: 8080
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film?serverTimezone=GMT
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
# 控制台显示SQL语句
      show-sql: true
  thymeleaf:
    cache: false
  http:
    multipart:
# 上传最大大小   上传图片时用到
      max-file-size: 100MB

imageFilePath: D://aacode//java//Film//src//main//resources//static//filmImages//